version: 2

project_name: lx

builds:
  - id: lx-build
    env:
      - CGO_ENABLED=1

    main: ./cmd/main.go
    binary: lx

    ldflags:
      - -s -w -X main.version={{.Version}}

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64

    ignore:
      - goos: windows
        goarch: arm64

    # [핵심] Docker 내부의 진짜 컴파일러(GCC/Clang) 연결
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=x86_64-linux-gnu-gcc
          - CXX=x86_64-linux-gnu-g++
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++
      - goos: darwin
        goarch: amd64
        env:
          - CC=o64-clang
          - CXX=o64-clang++
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang
          - CXX=oa64-clang++
      - goos: windows
        goarch: amd64
        env:
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  disable: true

brews:
  - repository:
      owner: chebread
      name: homebrew-lx
      branch: master
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    homepage: "https://github.com/chebread/lx"
    description: "Interface by Human, Logic by AI. A vibe coding tool under developer control."
    license: "AGPL-3.0"
    directory: Formula

    install: |
      bin.install "lx"

    test: |
      system "#{bin}/lx --version"
